= Asciidoc support for Wisdom

== Description

AsciiDoc is a human-readable document format, semantically equivalent to DocBook XML,
but using plain-text mark-up conventions. AsciiDoc documents can be created using any text editor and read “as-is”,
or rendered to HTML or any other format supported by a DocBook tool-chain.

The Ascidoc extension generates HTML documents from asciidoc files. It relies on the Asciidoctor(http://asciidoctor.org/)
 implementation. It supports the _watch_ mode, so every modification triggers the Asciidoc rendering.

== Installation

The asciidoc support is a build-process extension. In the +plugins+ section of your application +pom.xml+ file add:
----
<plugin>
    <groupId>org.wisdom-framework</groupId>
    <artifactId>wisdom-asciidoc-maven-plugin</artifactId>
    <version>${project.version}</version>
    <executions>
        <execution>
            <goals>
                <goal>compile-asciidoc</goal>
            </goals>
            <configuration>
                <stylesheet>github.css</stylesheet>
                <stylesheetDir>stylesheets</stylesheetDir>
            </configuration>
        </execution>
    </executions>
</plugin>
----

The plugin generates the HTML document for asciidoc files contained in the:

1. src/main/resources/assets directory
2. src/main/assets directory

It supports the _watch_ mode, so any change to a file is immediately processed and the document re-rendered.


== Usages

Using the plugin is very simple, just create +.ad+ file in +src/main/resources/assets+ or +/src/main/assets+,
they will be processed and the corresponding HTML document(s) created. The HTML documentation is served as the other
 static assets.

== Configuration

Asciidoc files are _filtered_, meaning that Maven properties are replaced in the file.

[options="header"]
|===
|Parameter
|Type
|Description

|backend
|String
|The Asciidoc backend, +html5+ by default.

|doctype
|String
|The type of document, +article+ by default.

|attributes
|Map
|The custom attributes given to the Asciidoc processor

|compact
|boolean
|Enables or disables the compact mode (false by default)

|embedAssets
|Map
|The custom attributes given to the Asciidoc processor

|imagesDir
|String
|The relative directory containing the images.

|headerFooter
|boolean
|Enables or disabled the header and the footer, default to true.

|sourceHighlighter
|String
|The syntax highlighter (Coderay or highlighjs)

|templateDir
|File
|Template directory (no template by default)

|templateEngine
|String
|The template engine (no template engine by default)

|extensions
|List of String
|The list of custom file extensions that need to be compiled using the Asciidoc processor. By default +.ad+, +.adoc+
and +.asciidoc+ are rendered.

|===




